// Copyright 2026 The KitOps Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package unpack

import (
	"context"
	"fmt"

	"github.com/kitops-ml/kitops/pkg/artifact"
	"github.com/kitops-ml/kitops/pkg/lib/constants"
	"github.com/kitops-ml/kitops/pkg/lib/constants/mediatype"
	"github.com/kitops-ml/kitops/pkg/lib/filesystem"
	"github.com/kitops-ml/kitops/pkg/lib/kitfile"
	"github.com/kitops-ml/kitops/pkg/output"
	"oras.land/oras-go/v2"

	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
)

// legacyUnpackLayers exists to support ModelKits created before KitOps v0.5.0, when LayerInfo
// was added. Prior to this, no LayerInfo is available on Kitfiles, so determining the path for
// layers requires matching manifests to Kitfile elements in order.
func legacyUnpackLayers(ctx context.Context, store oras.ReadOnlyTarget, manifest *ocispec.Manifest, config *artifact.KitFile, opts *UnpackOptions) error {
	// Since there might be multiple datasets, etc. we need to synchronously iterate
	// through the config's relevant field to get the correct path for unpacking
	// We need to support older ModelKits (that were packed without diffIDs and digest
	// in the config) for now, so we need to continue using the old structure.
	var modelPartIdx, codeIdx, datasetIdx, docsIdx, promptIdx int
	didUnpackModel := false
	for _, layerDesc := range manifest.Layers {
		// This variable supports older-format tar layers (that don't include the
		// layer path). For current ModelKits, this will be empty
		var relPath string

		mediaType, err := mediatype.ParseMediaType(layerDesc.MediaType)
		if err != nil {
			// We may encounter unknown media types while unpacking ModelPacks, e.g. we include Kitfiles
			// which are not ModelPack mediatypes
			output.Logf(output.LogLevelWarn, "Unknown media type %s: skipping unpack", layerDesc.MediaType)
			continue
		}

		// Grab path + layer info from the config object corresponding to this layer
		var layerPath string
		var layerInfo *artifact.LayerInfo

		// Note: ModelPack artifacts may have multiple layers with the basetype for models (i.e. multiple model.weight layers),
		// if they have been generated by other tooling (i.e. not by Kit). To support unpacking such artifacts, the generated
		// Kitfile for that artifact will store model weight layers after the first as model parts (which normally correspond)
		// to the model.config ModelPack mediatype). After the first model layer has been unpacked, we need to look at modelparts
		// for additional layers.
		switch mediaType.Base() {
		case mediatype.ModelBaseType:
			if !didUnpackModel {
				entry := config.Model
				didUnpackModel = true
				if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
					continue
				}
				layerInfo, layerPath = entry.LayerInfo, entry.Path
				output.Infof("Unpacking model %s to %s", config.Model.Name, config.Model.Path)
				break
			}
			// This is not the first ModelBaseType layer we've seen, need to fallthrough and find it in modelparts
			fallthrough

		case mediatype.ModelPartBaseType:
			entry := config.Model.Parts[modelPartIdx]
			modelPartIdx += 1
			if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
				continue
			}
			layerInfo, layerPath = entry.LayerInfo, entry.Path
			output.Infof("Unpacking model part %s to %s", entry.Name, entry.Path)

		case mediatype.CodeBaseType:
			// Code-type layers may be either regular code or prompts
			if layerDesc.Annotations[constants.LayerSubtypeAnnotation] == constants.LayerSubtypePrompt {
				entry := config.Prompts[promptIdx]
				promptIdx += 1
				if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
					continue
				}
				layerInfo, layerPath = entry.LayerInfo, entry.Path
				output.Infof("Unpacking prompt to %s", entry.Path)
			} else {
				entry := config.Code[codeIdx]
				codeIdx += 1
				if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
					continue
				}
				layerInfo, layerPath = entry.LayerInfo, entry.Path
				output.Infof("Unpacking code to %s", entry.Path)
			}

		case mediatype.DatasetBaseType:
			// Since some datasets may be remote, we need to search the Kitfile for the next non-remote dataset
			var entry *artifact.DataSet
			for idx := datasetIdx; idx < len(config.DataSets); idx++ {
				dataset := config.DataSets[idx]
				if dataset.RemotePath != "" {
					continue
				}
				entry = &dataset
				datasetIdx = idx + 1
				break
			}
			if entry == nil {
				continue
			}
			if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
				continue
			}
			layerInfo, layerPath = entry.LayerInfo, entry.Path
			output.Infof("Unpacking dataset %s to %s", entry.Name, entry.Path)

		case mediatype.DocsBaseType:
			entry := config.Docs[docsIdx]
			docsIdx += 1
			if !kitfile.LayerMatchesAnyFilter(entry, opts.FilterConfs) {
				continue
			}
			layerInfo, layerPath = entry.LayerInfo, entry.Path
			output.Infof("Unpacking docs to %s", entry.Path)

		case mediatype.ConfigBaseType:
			// ModelPacks may contain a Kitfile in their layers, which is unpacked separately
			continue

		case mediatype.UnknownBaseType:
			// Should never happen as we check earlier, but for completeness' sake:
			output.Logf(output.LogLevelWarn, "Unknown media type %s: skipping unpack", layerDesc.MediaType)
		}

		if layerInfo != nil {
			if layerInfo.Digest != layerDesc.Digest.String() {
				return fmt.Errorf("digest in config and manifest do not match in %s", mediaType.UserString())
			}
			relPath = ""
		} else {
			_, relPath, err = filesystem.VerifySubpath(opts.UnpackDir, layerPath)
			if err != nil {
				return fmt.Errorf("error resolving %s path: %w", mediaType.UserString(), err)
			}
		}

		if err := unpackLayer(ctx, store, layerDesc, opts.UnpackDir, relPath, opts.Overwrite, opts.IgnoreExisting, mediaType); err != nil {
			return fmt.Errorf("failed to unpack: %w", err)
		}
	}

	output.Debugf("Unpacked %d model part layers", modelPartIdx)
	output.Debugf("Unpacked %d code layers", codeIdx)
	output.Debugf("Unpacked %d dataset layers", datasetIdx)
	output.Debugf("Unpacked %d docs layers", docsIdx)
	output.Debugf("Unpacked %d prompt layers", promptIdx)

	return nil
}
