// Copyright 2024 The KitOps Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package ignore

import "strings"

// OsSpecificFiles contains filenames that are auto-generated by operating systems
// and should be ignored by KitOps when scanning the filesystem.
var OsSpecificFiles = []string{
	".DS_Store",       // macOS
	".AppleDouble",    // macOS
	".LSOverride",     // macOS
	".Spotlight-V100", // macOS
	".Trashes",        // macOS
	"Thumbs.db",       // Windows
	"desktop.ini",     // Windows
	"$RECYCLE.BIN",    // Windows
	"ehthumbs.db",     // Windows
}

// ShouldIgnoreFile returns true if the file is a known OS-generated metadata file
// that should not be included in Kitfile generation or layer packing.
func ShouldIgnoreFile(name string) bool {
	for _, osFile := range OsSpecificFiles {
		if strings.EqualFold(name, osFile) {
			return true
		}
	}
	return false
}
