name: Build the docs

on:
  # Runs on pull requests to the `main` branch and only for the `docs/**` path.
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PNPM_CACHE_STORE_PATH: ""

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version-file: './docs/.nvmrc'

      - uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # 6.0.7
        name: Install pnpm
        with:
          run_install: false
          package_json_file: './docs/package.json'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "PNPM_CACHE_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_CACHE_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd docs
          pnpm install

      - name: Build the docs
        run: |
          cd docs
          pnpm docs:build
