name: Kubeflow Components Tests

on:
  pull_request:
    paths:
      - 'build/dockerfiles/kubeflow-components/**'
      - '.github/workflows/kubeflow-components-test.yaml'

jobs:
  test-scripts:
    name: Run BATS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install BATS
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run push-modelkit tests
        working-directory: build/dockerfiles/kubeflow-components
        run: bats tests/push-modelkit.bats

      - name: Run unpack-modelkit tests
        working-directory: build/dockerfiles/kubeflow-components
        run: bats tests/unpack-modelkit.bats

  test-container-build:
    name: Test container build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8    # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c  # v4.2.0

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check kubeflow components container build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a    # v7.3.0
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          context: build/dockerfiles/kubeflow-components
          file: build/dockerfiles/kubeflow-components/Dockerfile
          build-args: |
            KIT_BASE_IMAGE=ghcr.io/kitops-ml/kitops:next
