name: Container entrypoint tests

on:
  pull_request:
    branches: [ main ]

jobs:
  entrypoint-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build test container
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0    # v6.17.0
        with:
          context: ./build
          file: ./build/ci/Dockerfile
          push: false
          tags: entrypoint-tests

      - name: Run Bats tests
        run: |
          docker run --rm entrypoint-tests
