name: Container entrypoint tests

on:
  pull_request:
    branches: [ main ]

jobs:
  entrypoint-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build test container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83    # v6.18.0
        with:
          context: ./build
          file: ./build/ci/Dockerfile
          push: false
          tags: entrypoint-tests

      - name: Run Bats tests
        run: |
          docker run --rm entrypoint-tests
